### ISSUE TITLE
Hang on npm run webpack

### ISSUE THREAD

**Issue by gaelicmichael** [C-JSN/D3-ID3#76]
NPM never seems to complete or return when I issue “npm run webpack”

**Comment by smeads** [comment]
@gaelicmichael sorry for the delayed reply. 

I usually open 2 terminal windows (tabs). The first one I will run `npm run webpack`. I'll keep it running so I don't have to run it each time I make updates to the code. If you want webpack to stop running just type the following command `ctrl + c` in your terminal. The second terminal window I'll run `npm run dev-start`. Again, I'll leave this running as well and use same command as above to quite it's runtime. However, if I make any changes to the `package.json` file then you'll have to re-run both commands to see the reflected changes.

Hopefully this answers your question. If not, please let me know.
